const $=s=>document.querySelector(s);let current=null;
const adversarialDemo=`REQUEST FOR PROPOSALS
Facilities Energy Upgrade Program
Responses must be received by October 16, 2026 at 4:00 PM ET. Offerors shall submit the signed proposal form and proof of insurance. A site visit is optional and vendors may attend on October 5, 2026 at 10:00 AM. Respondents should describe relevant experience and may include additional case studies if useful. The owner may request clarifications after evaluation. Pricing is requested for the base scope and alternates should be identified separately. The selected contractor will be required to provide a project schedule before notice to proceed. Preference may be given to teams with prior municipal experience. Questions are encouraged and should be submitted by October 8, 2026. Failure to include the signed proposal form will result in rejection.`;
const demo=`REQUEST FOR PROPOSALS\nSolar + Battery Energy Storage Project\nProposals must be received by September 30, 2026 at 5:00 PM ET. The bidder shall provide evidence of at least three comparable projects completed within the past five years. Bidder must submit a project schedule, pricing workbook, safety plan, proof of insurance, and references. The proposed system shall include not less than 5 MW of battery storage. Vendors are required to identify all subcontractors. Questions must be submitted no later than September 22, 2026. A mandatory pre-bid conference will be held September 20, 2026 at 10:00 AM. Failure to provide the signed certification form may result in rejection. The owner may request clarifications. Final engineering and permitting are the responsibility of the selected contractor.`;
const splitSentences=t=>t.replace(/\r/g,' ').split(/(?<=[.!?])\s+|\n+/).map(s=>s.trim()).filter(s=>s.length>8);
function analyzeText(t){const sentences=splitSentences(t),req=[],dates=[],evidence=[],flags=[];const hard=/\b(shall|must|required to|mandatory|will be rejected|will result in rejection|condition of participation|failure to (?:provide|comply|include)|not less than|no later than)\b/i;const soft=/\b(should|may|could|encouraged|preferred|desirable|optional|at its discretion|subject to|if available|if useful|where possible|preference may)\b/i;const instruction=/\b(provide|submit|demonstrate|describe|identify|include|complete|attach|certif|proof|evidence|references?|insurance|schedule|pricing|workbook|plan)\b/i;const dateRx=/\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+\d{1,2}(?:,\s*\d{4})?(?:\s+(?:at\s+)?\d{1,2}:\d{2}\s*(?:AM|PM)?(?:\s*[A-Z]{2,4})?)?/ig;sentences.forEach((s,i)=>{const hardHit=hard.test(s),softHit=soft.test(s),inst=instruction.test(s);let classification=hardHit&&!softHit?'MANDATORY':'REVIEW';if(hardHit&&softHit)classification='AMBIGUOUS';if(hardHit||inst||softHit)req.push({id:`R${String(req.length+1).padStart(3,'0')}`,mandatory:classification==='MANDATORY',classification,text:s,source:`Sentence ${i+1}`});if(inst)evidence.push({text:s,source:`Sentence ${i+1}`});(s.match(dateRx)||[]).forEach(d=>dates.push({date:d,context:s,source:`Sentence ${i+1}`}));if(softHit||classification==='AMBIGUOUS'||/\b(clarif|addend|amend)\b/i.test(s))flags.push({text:s,source:`Sentence ${i+1}`,reason:classification==='AMBIGUOUS'?'Mixed mandatory/advisory language — resolve against the authoritative solicitation.':'Conditional, advisory or change-sensitive language — human review recommended.'});});if(!dates.length)flags.push({text:'No explicit calendar dates detected.',source:'Automated check',reason:'Verify the full pack for deadlines, addenda and question periods.'});if(!/addend|amend/i.test(t))flags.push({text:'No addendum/amendment reference detected in supplied text.',source:'Automated check',reason:'Confirm separately whether amendments or addenda exist.'});return{id:'BF-'+new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14),created:new Date().toISOString(),requirements:req,dates,evidence:[...new Map(evidence.map(x=>[x.text,x])).values()],flags,sourceLength:t.length};}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function row(title,body,cls='',small=''){return `<div class="row ${cls}"><strong>${esc(title)}</strong><div>${esc(body)}</div>${small?`<small>${esc(small)}</small>`:''}</div>`}
async function fingerprint(text){try{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,20)}catch{return 'local-'+text.length}}
const RC4_POLICY={capability:'bid-foundry',version:'RC4',requiredScope:'analyze',allowed:['analyze','extract_requirements','build_compliance_matrix','package_results'],humanRelease:['submit_proposal','commit_funds','represent_company','publish_externally']};
function authorizeInvocation({principal,agent,scope=[],delegation='active',action='analyze'}){
 const receipt={principal,agent,action,delegation,scope:[...scope],capability:RC4_POLICY.capability,version:RC4_POLICY.version,authorized:false,humanReleaseRequired:RC4_POLICY.humanRelease.includes(action),reason:null,timestamp:new Date().toISOString()};
 if(!principal||!agent){receipt.reason='IDENTITY_REQUIRED';return receipt}
 if(delegation==='expired'){receipt.reason='DELEGATION_EXPIRED';return receipt}
 if(delegation==='revoked'){receipt.reason='DELEGATION_REVOKED';return receipt}
 if(RC4_POLICY.humanRelease.includes(action)){receipt.reason='HUMAN_RELEASE_REQUIRED';return receipt}
 if(!scope.includes(RC4_POLICY.requiredScope)){receipt.reason='SCOPE_DENIED';return receipt}
 if(!RC4_POLICY.allowed.includes(action)){receipt.reason='ACTION_NOT_ALLOWED';return receipt}
 receipt.authorized=true;receipt.reason='AUTHORIZED';return receipt;
}
function runAuthorizationRegression(){
 const cases=[
  {name:'authorized-analysis',input:{principal:'local-human-principal',agent:'BidFoundry-Agent-RC4',scope:['analyze'],delegation:'active',action:'analyze'},expect:'AUTHORIZED'},
  {name:'missing-scope',input:{principal:'local-human-principal',agent:'BidFoundry-Agent-RC4',scope:[],delegation:'active',action:'analyze'},expect:'SCOPE_DENIED'},
  {name:'expired-delegation',input:{principal:'local-human-principal',agent:'BidFoundry-Agent-RC4',scope:['analyze'],delegation:'expired',action:'analyze'},expect:'DELEGATION_EXPIRED'},
  {name:'revoked-delegation',input:{principal:'local-human-principal',agent:'BidFoundry-Agent-RC4',scope:['analyze'],delegation:'revoked',action:'analyze'},expect:'DELEGATION_REVOKED'},
  ...RC4_POLICY.humanRelease.map(action=>({name:'blocked-'+action,input:{principal:'local-human-principal',agent:'BidFoundry-Agent-RC4',scope:['analyze'],delegation:'active',action},expect:'HUMAN_RELEASE_REQUIRED'}))
 ];
 return cases.map(c=>{const receipt=authorizeInvocation(c.input);return{name:c.name,pass:receipt.reason===c.expect,expect:c.expect,receipt}});
}
window.BidFoundryRC4={policy:RC4_POLICY,authorizeInvocation,runAuthorizationRegression};
function gatewayLog(msg,cls='allowed'){const el=$('#execLog');if(el)el.insertAdjacentHTML('beforeend',`<div class="logline"><span class="${cls}">●</span> ${esc(msg)}</div>`)}
async function render(c){current=c;$('#resultTitle').textContent='Evidence pass complete — human review required.';$('#caseId').textContent=c.id;const m=$('#metrics').children;m[0].querySelector('strong').textContent=c.requirements.length;m[1].querySelector('strong').textContent=c.requirements.filter(x=>x.mandatory).length;m[2].querySelector('strong').textContent=c.dates.length;m[3].querySelector('strong').textContent=c.flags.length;$('#dates').innerHTML=c.dates.length?c.dates.map(x=>row(x.date,x.context,'',x.source)).join(''):row('No explicit dates found','Verify the complete solicitation pack manually.','flag');$('#requirements').innerHTML=c.requirements.length?c.requirements.map(x=>row(`${x.id} · ${x.classification==='MANDATORY'?'MANDATORY / GATE':x.classification==='AMBIGUOUS'?'AMBIGUOUS / REVIEW':'INSTRUCTION / REVIEW'}`,x.text,x.mandatory?'mandatory':'',x.source)).join(''):row('No obligation patterns detected','Manual review is required.','flag');$('#evidence').innerHTML=c.evidence.length?c.evidence.map((x,i)=>row(`E${String(i+1).padStart(3,'0')}`,x.text,'',x.source)).join(''):row('No requested-evidence patterns detected','Review forms, annexes and attachments manually.','flag');$('#flags').innerHTML=c.flags.map(x=>row(x.reason,x.text,'flag',x.source)).join('');$('#empty').hidden=true;$('#output').hidden=false;const gates=[...document.querySelectorAll('.gate')];for(let i=2;i<=5;i++)gates[i]?.classList.add('ok');gates[2].querySelector('small').textContent='Source received';gates[3].querySelector('small').textContent='Requirements extracted';gates[4].querySelector('small').textContent='Checklist ready';gates[5].querySelector('small').textContent='Receipt recorded';$('#gatewayStatus').textContent='Analysis complete. Awaiting human release.';const fp=await fingerprint($('#sourceText').value);$('#sourceHash').textContent=fp;$('#receiptId').textContent=`${c.id}:${fp.slice(0,8)}`;gatewayLog(`Source accepted (${c.sourceLength} characters)`);gatewayLog(`${c.requirements.length} requirement candidates extracted`);gatewayLog('Evidence receipt generated');gatewayLog('External action blocked pending human release','denied');c.gateway={principal:'local-human-principal',agent:'BidFoundry-Agent-RC4',scope:['analyze','extract_requirements','build_compliance_matrix','package_results'],denied:['submit_proposal','commit_funds','represent_company','publish_externally'],authorization:'ANALYZE_ONLY',sourceFingerprint:fp,humanReleaseRequired:true};}
const analyzeBtn=$('#analyze'),demoBtn=$('#demo'),clearBtn=$('#clear'),sourceBox=$('#sourceText');
function setRunState(state,message){if(analyzeBtn){analyzeBtn.disabled=state==='running';analyzeBtn.textContent=state==='running'?'ANALYZING…':'ANALYZE WITH JAKEAI'}if(message&&$('#gatewayStatus'))$('#gatewayStatus').textContent=message}
async function runAnalysis(){const auth=authorizeInvocation({principal:'local-human-principal',agent:'BidFoundry-Agent-RC4',scope:['analyze','extract_requirements','build_compliance_matrix','package_results'],delegation:'active',action:'analyze'});gatewayLog(`Authorization: ${auth.reason}`,auth.authorized?'allowed':'denied');if(!auth.authorized){setRunState('error',`Authorization blocked: ${auth.reason}`);return}const t=sourceBox.value.trim();if(!t){setRunState('idle','Source required before analysis.');sourceBox.focus();return}setRunState('running','Analyzing supplied source…');gatewayLog('Analysis requested');try{await render(analyzeText(t));setRunState('done','Analysis complete. Awaiting human release.');$('#results-panel')?.scrollIntoView({behavior:'smooth',block:'start'});}catch(err){console.error(err);setRunState('error','Analysis error — no external action occurred.');gatewayLog('Analysis failed locally: '+(err?.message||'unknown error'),'denied');}}
if(analyzeBtn)analyzeBtn.addEventListener('click',runAnalysis);
if(demoBtn)demoBtn.addEventListener('click',()=>{sourceBox.value=demo;setRunState('idle','Demo source loaded. Press Analyze with JakeAI.');gatewayLog('Demo source loaded — analysis not yet run');sourceBox.scrollIntoView({behavior:'smooth',block:'center'});});
if(demoBtn)demoBtn.addEventListener('contextmenu',e=>{e.preventDefault();sourceBox.value=adversarialDemo;setRunState('idle','Mixed-language regression source loaded. Press Analyze with JakeAI.');});
if(clearBtn)clearBtn.addEventListener('click',()=>location.reload());
$('#fileInput')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(f){sourceBox.value=await f.text();setRunState('idle','TXT source loaded. Ready to analyze.')}});
function dl(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}$('#json').onclick=()=>current&&dl(`${current.id}.json`,JSON.stringify(current,null,2),'application/json');$('#csv').onclick=()=>{if(!current)return;const q=s=>'"'+String(s).replaceAll('"','""')+'"';const rows=[['ID','Mandatory','Requirement','Source'],...current.requirements.map(x=>[x.id,x.mandatory?'YES':'NO',x.text,x.source])];dl(`${current.id}-checklist.csv`,rows.map(r=>r.map(q).join(',')).join('\n'),'text/csv')};